version: 0.2

#env:
#  variables:
#    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#  parameter-store:
#    LOGIN_PASSWORD: "dockerLoginPassword"

phases:
#  install:
#    commands:
#      - echo Entered the install phase...
#      - apt-get update -y
#      - apt-get install -y maven
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - chmod x+u gradlew
      - gradle -version
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - ls -al
      - gradle build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/trial-*.jar
  discard-paths: yes